---
title: "Penguin Bill Length Analysis (Python)"
author: "Edmund Yong"
date: "2026/09/21"
format: 
  html:
    code-fold: true
jupyter: python3
---

## Goal
The goal of this post is to showcase the varying bill lengths in millimeters for different penguin species by sex.

### Data Source
The data used in this post is sourced from the [Palmer Penguins](https://allisonhorst.github.io/palmerpenguins/) dataset shown below in @tbl-palmerpenguins-dataset.

```{python}
#| label: tbl-palmerpenguins-dataset
#| tbl-cap: "Palmer Penguins Dataset"
import pandas as pd
import matplotlib.pyplot as plt
from palmerpenguins import load_penguins

penguins = load_penguins()

penguins.head()
```

### Data Cleanup

The cleaned data can be found below in @tbl-penguin-bill-length. To clean the data, records without a recorded sex were removed from the original dataset. The mean of the penguins' bill length was then calculated after grouping by the penguins' species and sex.

```{python}
#| label: tbl-penguin-bill-length
#| tbl-cap: "Bill length of penguins by species (Table)."
#| message: false
#| warning: false
modified_penguins = penguins.dropna(subset='sex').groupby(by=['species', 'sex'])['bill_length_mm'].mean().unstack()

modified_penguins
```

### Findings
After cleaning the data and viewing the data it in @fig-penguin-bill-length below, it can be observed that male penguins on average across the listed species have longer bills compared to female penguins.

```{python}
#| label: fig-penguin-bill-length
#| fig-cap: "Bill length of penguins by species (Chart)."
#| message: false
#| warning: false
modified_penguins.plot(kind="bar")

plt.xlabel("Species")
plt.ylabel("Bill Length (mm)")
plt.xticks(rotation=0)
plt.legend(title="Sex")
plt.grid(axis="y")
plt.tight_layout()
plt.show()
```
Data: [Palmer Penguins](https://allisonhorst.github.io/palmerpenguins/),
Palmer Station Antarctica LTER.
